INSERT INTO employees (fullName, employeeId, department, dutyStation, position, employmentStatus, profilePicture, createdAt, updatedAt) VALUES
('John Doe', 'EMP001', 'IT', 'Monrovia HQ', 'Software Engineer', 'Active', 'https://randomuser.me/api/portraits/men/1.jpg', NOW(), NOW()),
('Jane Smith', 'EMP002', 'Finance', 'Monrovia HQ', 'Accountant', 'Active', 'https://randomuser.me/api/portraits/women/2.jpg', NOW(), NOW()),
('Samuel Johnson', 'EMP003', 'HR', 'Buchanan Branch', 'HR Manager', 'Active', 'https://randomuser.me/api/portraits/men/3.jpg', NOW(), NOW()),
('Alice Cooper', 'EMP004', 'Procurement', 'Gbarnga Branch', 'Procurement Officer', 'Active', 'https://randomuser.me/api/portraits/women/4.jpg', NOW(), NOW()),
('Michael Brown', 'EMP005', 'IT', 'Monrovia HQ', 'System Admin', 'Active', 'https://randomuser.me/api/portraits/men/5.jpg', NOW(), NOW()),
('Nancy Drew', 'EMP006', 'Finance', 'Gbarnga Branch', 'Finance Officer', 'Active', 'https://randomuser.me/api/portraits/women/6.jpg', NOW(), NOW()),
('Chris Evans', 'EMP007', 'Operations', 'Monrovia HQ', 'Operations Manager', 'Active', 'https://randomuser.me/api/portraits/men/7.jpg', NOW(), NOW()),
('Sarah White', 'EMP008', 'IT', 'Monrovia HQ', 'Frontend Developer', 'Active', 'https://randomuser.me/api/portraits/women/8.jpg', NOW(), NOW()),
('David Lee', 'EMP009', 'Finance', 'Buchanan Branch', 'Finance Analyst', 'Active', 'https://randomuser.me/api/portraits/men/9.jpg', NOW(), NOW()),
('Emily Clark', 'EMP010', 'HR', 'Monrovia HQ', 'HR Assistant', 'Active', 'https://randomuser.me/api/portraits/women/10.jpg', NOW(), NOW()),
('Peter Parker', 'EMP011', 'IT', 'Monrovia HQ', 'Backend Developer', 'Active', 'https://randomuser.me/api/portraits/men/11.jpg', NOW(), NOW()),
('Linda Scott', 'EMP012', 'Finance', 'Gbarnga Branch', 'Auditor', 'Active', 'https://randomuser.me/api/portraits/women/12.jpg', NOW(), NOW()),
('Robert King', 'EMP013', 'Operations', 'Buchanan Branch', 'Logistics Officer', 'Active', 'https://randomuser.me/api/portraits/men/13.jpg', NOW(), NOW()),
('Grace Adams', 'EMP014', 'Procurement', 'Monrovia HQ', 'Procurement Assistant', 'Active', 'https://randomuser.me/api/portraits/women/14.jpg', NOW(), NOW()),
('Thomas Baker', 'EMP015', 'IT', 'Monrovia HQ', 'Network Engineer', 'Active', 'https://randomuser.me/api/portraits/men/15.jpg', NOW(), NOW()),
('Olivia Green', 'EMP016', 'HR', 'Gbarnga Branch', 'Recruiter', 'Active', 'https://randomuser.me/api/portraits/women/16.jpg', NOW(), NOW()),
('James Wright', 'EMP017', 'Finance', 'Monrovia HQ', 'Treasury Officer', 'Active', 'https://randomuser.me/api/portraits/men/17.jpg', NOW(), NOW()),
('Sophia Turner', 'EMP018', 'Operations', 'Buchanan Branch', 'Operations Officer', 'Active', 'https://randomuser.me/api/portraits/women/18.jpg', NOW(), NOW()),
('Daniel Hill', 'EMP019', 'IT', 'Monrovia HQ', 'DevOps Engineer', 'Active', 'https://randomuser.me/api/portraits/men/19.jpg', NOW(), NOW()),
('Chloe Mitchell', 'EMP020', 'Finance', 'Gbarnga Branch', 'Payroll Officer', 'Active', 'https://randomuser.me/api/portraits/women/20.jpg', NOW(), NOW()),
('Ethan Allen', 'EMP021', 'IT', 'Monrovia HQ', 'Full Stack Developer', 'Active', 'https://randomuser.me/api/portraits/men/21.jpg', NOW(), NOW()),
('Isabella Lopez', 'EMP022', 'HR', 'Buchanan Branch', 'HR Specialist', 'Active', 'https://randomuser.me/api/portraits/women/22.jpg', NOW(), NOW()),
('Matthew Carter', 'EMP023', 'Operations', 'Monrovia HQ', 'Supply Chain Manager', 'Active', 'https://randomuser.me/api/portraits/men/23.jpg', NOW(), NOW()),
('Ava Young', 'EMP024', 'Finance', 'Gbarnga Branch', 'Accounts Clerk', 'Active', 'https://randomuser.me/api/portraits/women/24.jpg', NOW(), NOW()),
('Lucas Hernandez', 'EMP025', 'IT', 'Monrovia HQ', 'Database Admin', 'Active', 'https://randomuser.me/api/portraits/men/25.jpg', NOW(), NOW()),
('Mia Gonzalez', 'EMP026', 'Procurement', 'Monrovia HQ', 'Procurement Analyst', 'Active', 'https://randomuser.me/api/portraits/women/26.jpg', NOW(), NOW()),
('Henry Walker', 'EMP027', 'Finance', 'Buchanan Branch', 'Budget Officer', 'Active', 'https://randomuser.me/api/portraits/men/27.jpg', NOW(), NOW()),
('Ella Hall', 'EMP028', 'IT', 'Monrovia HQ', 'UI/UX Designer', 'Active', 'https://randomuser.me/api/portraits/women/28.jpg', NOW(), NOW()),
('Jack Allen', 'EMP029', 'HR', 'Gbarnga Branch', 'Training Officer', 'Active', 'https://randomuser.me/api/portraits/men/29.jpg', NOW(), NOW()),
('Scarlett Wood', 'EMP030', 'Finance', 'Monrovia HQ', 'Financial Controller', 'Active', 'https://randomuser.me/api/portraits/women/30.jpg', NOW(), NOW()),
('Leo Martin', 'EMP031', 'IT', 'Monrovia HQ', 'Security Analyst', 'Active', 'https://randomuser.me/api/portraits/men/31.jpg', NOW(), NOW()),
('Zoe Ramirez', 'EMP032', 'HR', 'Buchanan Branch', 'HR Generalist', 'Active', 'https://randomuser.me/api/portraits/women/32.jpg', NOW(), NOW()),
('Ryan Cooper', 'EMP033', 'Operations', 'Monrovia HQ', 'Fleet Manager', 'Active', 'https://randomuser.me/api/portraits/men/33.jpg', NOW(), NOW()),
('Amelia Perry', 'EMP034', 'Finance', 'Gbarnga Branch', 'Tax Officer', 'Active', 'https://randomuser.me/api/portraits/women/34.jpg', NOW(), NOW()),
('Nathan Reed', 'EMP035', 'IT', 'Monrovia HQ', 'QA Engineer', 'Active', 'https://randomuser.me/api/portraits/men/35.jpg', NOW(), NOW()),
('Victoria Brooks', 'EMP036', 'Procurement', 'Buchanan Branch', 'Procurement Specialist', 'Active', 'https://randomuser.me/api/portraits/women/36.jpg', NOW(), NOW()),
('Oliver Hughes', 'EMP037', 'Finance', 'Monrovia HQ', 'Audit Manager', 'Active', 'https://randomuser.me/api/portraits/men/37.jpg', NOW(), NOW()),
('Lily Foster', 'EMP038', 'IT', 'Monrovia HQ', 'Technical Support', 'Active', 'https://randomuser.me/api/portraits/women/38.jpg', NOW(), NOW()),
('William Cook', 'EMP039', 'HR', 'Gbarnga Branch', 'Employee Relations Officer', 'Active', 'https://randomuser.me/api/portraits/men/39.jpg', NOW(), NOW()),
('Hannah Bell', 'EMP040', 'Finance', 'Monrovia HQ', 'Chief Accountant', 'Active', 'https://randomuser.me/api/portraits/women/40.jpg', NOW(), NOW());
